import { TagFilled } from '@ant-design/icons';

export const renderForm = [
  {
    label: 'ข้อมูลสาขา',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: 'active',
    label: 'เปิดใช้งาน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SwitchFormField',
    require: true,
  },
  {
    name: 'fromType',
    label: 'ประเภทธุรกิจ',
    col: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'RadioFormField',
    options: [
      { value: 'OrdinaryPerson', label: 'บุคคลธรรมดา' },
      { value: 'JuristicPerson', label: 'นิติบุคคล' },
    ],
    require: true,
  },
  {
    name: 'nameTh',
    label: 'ชื่อสาขา (ภาษไทย)',
    placeholder: 'กรอกชื่อสาขา',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'nameEn',
    label: 'ชื่อสาขา (English)',
    placeholder: 'กรอกชื่อสาขา',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'status',
    label: 'สถานะธุรกิจ',
    placeholder: 'สถานะธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'NewlyRegistered', label: 'ลูกค้าที่เพิ่งลงทะเบียนใหม่ในระบบ' },
      { value: 'ActiveUser', label: 'ลูกค้าที่ใช้งานอย่างต่อเนื่อง' },
      { value: 'LoyalCustomer', label: 'ลูกค้าที่มีความภักดีต่อระบบ' },
      { value: 'AtRisk', label: 'ลูกค้าที่อาจจะเสี่ยงต่อการหยุดใช้งาน' },
      { value: 'Churned', label: 'ลูกค้าที่ได้หยุดใช้บริการหรือยกเลิกบัญชี' },
    ],
    require: true,
  },
  {
    name: 'taxId',
    label: 'เลขทะเบียน 13 หลัก',
    placeholder: 'เลขทะเบียน 13 หลัก',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: 'logoUrl',
    label: 'ลิ้งค์โลโก้',
    placeholder: 'กรอกลิ้งค์โลโก้',
    require: true,
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'UploadFile',
  },
  {
    name: 'isMain',
    label: 'ประเภทสาขา',
    col: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'RadioFormField',
    options: [
      { value: true, label: 'สำนักงานใหญ่' },
      { value: false, label: 'สาขา' },
    ],
    require: true,
  },
  {
    name: 'type',
    label: 'รูปแบบธุรกิจ',
    placeholder: 'รูปแบบธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'CompanyLimited', label: 'บริษัทจำกัด' },
      { value: 'PublicCompanyLimited', label: 'บริษัทมหาชนจำกัด' },
      { value: 'LimitedPartnership', label: 'ห้างหุ้นส่วนจำกัด' },
      { value: 'Foundation', label: 'มูลนิธิ' },
      { value: 'Association', label: 'สมาคม' },
      { value: 'JointVenture', label: 'กิจการร่วมค้า' },
      { value: 'Others', label: 'อื่นๆ' },
    ],
    require: true,
  },
  {
    name: 'openingDate',
    label: 'วันที่จดทะเบียน',
    placeholder: 'วันที่จดทะเบียน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'DatePickerFormField',
  },
  {
    name: 'branchCode',
    label: 'รหัสสาขา',
    placeholder: 'รหัสสาขา',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: 'contactEmail',
    label: 'อีเมลล์',
    placeholder: 'กรอกอีเมลล์',
    col: { xs: 24, sm: 12, md: 12, lg: 6, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'websiteUrl',
    label: 'ลิ้งค์เว็ปไซต์',
    placeholder: 'กรอกลิ้งค์เว็ปไซต์',
    col: { xs: 24, sm: 12, md: 12, lg: 6, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactPhone',
    label: 'เบอร์โทรติดต่อ',
    placeholder: 'กรอกเบอร์โทร',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactFacebook',
    label: 'Facebook',
    placeholder: 'Facebook',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactLine',
    label: 'Line ID',
    placeholder: 'line Id',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactWhatsapp',
    label: 'WhatsApp',
    placeholder: 'WhatsApp',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactWebsite',
    label: 'เว็บไซต์ติดต่อ',
    placeholder: 'เว็บไซต์ติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactNote',
    label: 'ข้อมูลการติดต่อ',
    placeholder: 'ข้อมูลการติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'registerVat',
    label: 'จดทะเบียนภาษีมูลค่าเพิ่ม',
    placeholder: 'จดทะเบียนภาษีมูลค่าเพิ่ม',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 24 },
    type: 'SwitchFormField',
    require: true,
  },
  {
    name: 'descriptionsTh',
    label: 'คำอธิบายธุรกิจ (ภาษาไทย)',
    placeholder: 'คำอธิบายธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },
  {
    name: 'descriptionsEn',
    label: 'คำอธิบายธุรกิจ (English)',
    placeholder: 'คำอธิบายธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },
  {
    icon: <TagFilled />,
    label: 'ข้อมูลที่อยู่สาขา',
    col: { xs: 24, sm: 12, md: 12, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: ['address', 'active'],
    label: 'ทำงานอยู่',
    placeholder: 'ทำงานอยู่',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'SwitchFormField',
  },
  {
    name: ['address', 'status'],
    label: 'สถานะที่อยู่',
    placeholder: 'สถานะที่อยู่',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'NewlyRegistered', label: 'ลูกค้าที่เพิ่งลงทะเบียนใหม่ในระบบ' },
      { value: 'ActiveUser', label: 'ลูกค้าที่ใช้งานอย่างต่อเนื่อง' },
      { value: 'LoyalCustomer', label: 'ลูกค้าที่มีความภักดีต่อระบบ' },
      { value: 'AtRisk', label: 'ลูกค้าที่อาจจะเสี่ยงต่อการหยุดใช้งาน' },
      { value: 'Churned', label: 'ลูกค้าที่ได้หยุดใช้บริการหรือยกเลิกบัญชี' },
    ],
    require: true,
  },
  {
    name: ['address', 'descriptions'],
    label: 'คำอธิบาย',
    placeholder: 'กรอกคำอธิบาย',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'language'],
    label: 'ภาษา',
    placeholder: 'ภาษา',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: ['address', 'addressType'],
    label: 'ประเภทที่อยู่',
    placeholder: 'กรอกประเภทที่อยู่',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'isMain'],
    label: 'ที่อยู่หลัก',
    col: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'RadioFormField',
    options: [
      { value: true, label: 'หลัก' },
      { value: false, label: 'สาขา' },
    ],
    require: true,
  },
  {
    name: ['address', 'name'],
    label: 'ชื่อที่อยู่',
    placeholder: 'กรอกชื่อที่อยู่',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: ['address', 'province'],
    label: 'จังหวัด',
    placeholder: 'กรอกจังหวัด',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'district'],
    label: 'เขต',
    placeholder: 'กรอกเขต',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'subDistrict'],
    label: 'ตำบล',
    placeholder: 'กรอกตำบล',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'address'],
    label: 'ที่อยู่',
    placeholder: 'กรอกที่อยู่',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'postalCode'],
    label: 'รหัสไปรษณีย์',
    placeholder: 'รหัสไปรษณีย์',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
];

export const renderEditForm = [
  {
    label: 'ข้อมูลสาขา',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: 'active',
    label: 'เปิดใช้งาน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SwitchFormField',
    require: true,
  },
  {
    name: 'fromType',
    label: 'ประเภทธุรกิจ',
    col: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'RadioFormField',
    options: [
      { value: 'OrdinaryPerson', label: 'บุคคลธรรมดา' },
      { value: 'JuristicPerson', label: 'นิติบุคคล' },
    ],
    require: true,
  },
  {
    name: 'nameTh',
    label: 'ชื่อสาขา (ภาษไทย)',
    placeholder: 'กรอกชื่อสาขา',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'nameEn',
    label: 'ชื่อสาขา (English)',
    placeholder: 'กรอกชื่อสาขา',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'status',
    label: 'สถานะธุรกิจ',
    placeholder: 'สถานะธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'NewlyRegistered', label: 'ลูกค้าที่เพิ่งลงทะเบียนใหม่ในระบบ' },
      { value: 'ActiveUser', label: 'ลูกค้าที่ใช้งานอย่างต่อเนื่อง' },
      { value: 'LoyalCustomer', label: 'ลูกค้าที่มีความภักดีต่อระบบ' },
      { value: 'AtRisk', label: 'ลูกค้าที่อาจจะเสี่ยงต่อการหยุดใช้งาน' },
      { value: 'Churned', label: 'ลูกค้าที่ได้หยุดใช้บริการหรือยกเลิกบัญชี' },
    ],
    require: true,
  },
  {
    name: 'taxId',
    label: 'เลขทะเบียน 13 หลัก',
    placeholder: 'เลขทะเบียน 13 หลัก',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: 'logoUrl',
    label: 'ลิ้งค์โลโก้',
    placeholder: 'กรอกลิ้งค์โลโก้',
    require: true,
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'UploadFile',
  },
  {
    name: 'isMain',
    label: 'ประเภทสาขา',
    col: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'RadioFormField',
    options: [
      { value: true, label: 'สำนักงานใหญ่' },
      { value: false, label: 'สาขา' },
    ],
    require: true,
  },
  {
    name: 'type',
    label: 'รูปแบบธุรกิจ',
    placeholder: 'รูปแบบธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'CompanyLimited', label: 'บริษัทจำกัด' },
      { value: 'PublicCompanyLimited', label: 'บริษัทมหาชนจำกัด' },
      { value: 'LimitedPartnership', label: 'ห้างหุ้นส่วนจำกัด' },
      { value: 'Foundation', label: 'มูลนิธิ' },
      { value: 'Association', label: 'สมาคม' },
      { value: 'JointVenture', label: 'กิจการร่วมค้า' },
      { value: 'Others', label: 'อื่นๆ' },
    ],
    require: true,
  },
  {
    name: 'openingDate',
    label: 'วันที่จดทะเบียน',
    placeholder: 'วันที่จดทะเบียน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'DatePickerFormField',
  },
  {
    name: 'branchCode',
    label: 'รหัสสาขา',
    placeholder: 'รหัสสาขา',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: 'contactEmail',
    label: 'อีเมลล์',
    placeholder: 'กรอกอีเมลล์',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'websiteUrl',
    label: 'ลิ้งค์เว็ปไซต์',
    placeholder: 'กรอกลิ้งค์เว็ปไซต์',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactPhone',
    label: 'เบอร์โทรติดต่อ',
    placeholder: 'กรอกเบอร์โทร',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactFacebook',
    label: 'Facebook',
    placeholder: 'Facebook',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactLine',
    label: 'Line ID',
    placeholder: 'line Id',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactWhatsapp',
    label: 'WhatsApp',
    placeholder: 'WhatsApp',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactWebsite',
    label: 'เว็บไซต์ติดต่อ',
    placeholder: 'เว็บไซต์ติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactNote',
    label: 'ข้อมูลการติดต่อ',
    placeholder: 'ข้อมูลการติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'registerVat',
    label: 'จดทะเบียนภาษีมูลค่าเพิ่ม',
    placeholder: 'จดทะเบียนภาษีมูลค่าเพิ่ม',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 24 },
    type: 'SwitchFormField',
    require: true,
  },
  {
    name: 'descriptionsTh',
    label: 'คำอธิบายธุรกิจ (ภาษาไทย)',
    placeholder: 'คำอธิบายธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },
  {
    name: 'descriptionsEn',
    label: 'คำอธิบายธุรกิจ (English)',
    placeholder: 'คำอธิบายธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },
  {
    icon: <TagFilled />,
    label: 'ข้อมูลตามทะเบียน',
    col: { xs: 24, sm: 12, md: 12, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: ['address', 'active'],
    label: 'ทำงานอยู่',
    placeholder: 'ทำงานอยู่',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'SwitchFormField',
  },
  {
    name: ['address', 'status'],
    label: 'สถานะที่อยู่',
    placeholder: 'สถานะที่อยู่',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'NewlyRegistered', label: 'ลูกค้าที่เพิ่งลงทะเบียนใหม่ในระบบ' },
      { value: 'ActiveUser', label: 'ลูกค้าที่ใช้งานอย่างต่อเนื่อง' },
      { value: 'LoyalCustomer', label: 'ลูกค้าที่มีความภักดีต่อระบบ' },
      { value: 'AtRisk', label: 'ลูกค้าที่อาจจะเสี่ยงต่อการหยุดใช้งาน' },
      { value: 'Churned', label: 'ลูกค้าที่ได้หยุดใช้บริการหรือยกเลิกบัญชี' },
    ],
    require: true,
  },
  {
    name: ['address', 'descriptions'],
    label: 'คำอธิบาย',
    placeholder: 'กรอกคำอธิบาย',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'language'],
    label: 'ภาษา',
    placeholder: 'ภาษา',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: ['address', 'addressType'],
    label: 'ประเภทที่อยู่',
    placeholder: 'กรอกประเภทที่อยู่',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'isMain'],
    label: 'ที่อยู่หลัก',
    col: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'RadioFormField',
    options: [
      { value: true, label: 'หลัก' },
      { value: false, label: 'สาขา' },
    ],
    require: true,
  },
  {
    name: ['address', 'name'],
    label: 'ชื่อที่อยู่',
    placeholder: 'กรอกชื่อที่อยู่',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: ['address', 'province'],
    label: 'จังหวัด',
    placeholder: 'กรอกจังหวัด',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'district'],
    label: 'เขต',
    placeholder: 'กรอกเขต',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'subDistrict'],
    label: 'ตำบล',
    placeholder: 'กรอกตำบล',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'address'],
    label: 'ที่อยู่',
    placeholder: 'กรอกที่อยู่',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'postalCode'],
    label: 'รหัสไปรษณีย์',
    placeholder: 'รหัสไปรษณีย์',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
];
